[tox]
requires =
    tox>=4.2
env_list =
    py
    lint
    coverage-report
    docs
    check-packaging

[testenv]
runner = uv-venv-lock-runner
description = Setup base environment for {envname}

[testenv:py]
description = Run pytest with coverage
commands =
    coverage run -m pytest --doctest-glob=docs/usage.rst {tty:--color=yes} {posargs}
dependency_groups = test

[testenv:lint]
description = Lint codebase by running pre-commit.
package = skip
commands =
    prek run --all-files
dependency_groups = lint

[testenv:coverage-report]
description = Compile coverage from each test run.
commands =
    coverage report
depends =
    py
dependency_groups = test

[testenv:docs]
description = Check docs build
commands =
    make docs
allowlist_externals =
    make
dependency_groups = docs

[testenv:check-packaging]
description = Check packaging
commands =
    make check-build
allowlist_externals =
    make
dependency_groups = build docs
