name: "Python CI"

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Run tox
        uses: lsst-sqre/run-tox@c8c881a52dfa4e98e55817bac3195df8b0db715c # v1
        with:
          python-version: ${{ matrix.python }}
          tox-envs: "lint"

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Run tox
        uses: lsst-sqre/run-tox@c8c881a52dfa4e98e55817bac3195df8b0db715c # v1
        with:
          python-version: ${{ matrix.python }}
          tox-envs: "py,coverage-report"

  check-docs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - name: Run tox
        uses: lsst-sqre/run-tox@c8c881a52dfa4e98e55817bac3195df8b0db715c # v1
        with:
          python-version: ${{ matrix.python }}
          tox-envs: "docs"

  test-packaging:
    runs-on: ubuntu-latest
    needs: [lint, test, check-docs]

    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - name: Run tox
        uses: lsst-sqre/run-tox@c8c881a52dfa4e98e55817bac3195df8b0db715c # v1
        with:
          python-version: ${{ matrix.python }}
          tox-envs: "check-packaging"
