name: "Python CI"

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  ci:
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    uses: mareuter/shared-workflows/.github/workflows/uv-python-ci.yaml@main
    with:
      python-version: ${{ matrix.python }}

  check-docs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          python-version: ${{ matrix.python }}

      - name: Run tox
        run: uv run --only-group=tox tox run -e docs

  test-packaging:
    runs-on: ubuntu-latest
    needs: [ci, check-docs]

    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          python-version: ${{ matrix.python }}

      - name: Run tox
        run: uv run --only-group=tox tox run -e check-packaging
