name: "Upload Python Package"

on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        fetch-depth: 0

    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        uv sync --frozen --only-group=build

    - name: Build and publish to PyPi
      if: ${{ github.event_name != 'workflow_dispatch' }}
      run: |
        uv build
        uv publish

    - name: Build and publish to Test PyPi
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        uv build
        uv publish --index testpypi
